version: '3.5'

services:
  db:
    image: postgres
    restart: always
    hostname: ${POSTGRES_HOST}
    container_name: postgresDB
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - nest-docker-compose-example-network

  pgadmin4:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    ports:
      - '${PGADMIN_LISTEN_PORT}:80'
    networks:
      - nest-docker-compose-example-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:9876'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nest-docker-compose-example-network

networks:
  nest-docker-compose-example-network:
    driver: bridge
